---

- name: Ensure elasticsearch certificate exists
  ansible.builtin.stat:
    path: "/etc/elasticsearch/certs/{{ ansible_hostname }}.p12"
  register: elasticsearch_cert_exists
  when: not elasticsearch_manage_ca | bool

- name: Fail if elasticsearch certificate does not exist
  ansible.builtin.fail:
    msg: "Elasticsearch certificate not found at /etc/elasticsearch/certs/{{ ansible_hostname }}.p12"
  when:
    - not elasticsearch_manage_ca | bool
    - not elasticsearch_cert_exists.stat.exists

- name: Start Elasticsearch for security tasks
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
  register: elasticsearch_freshstart_security

- name: Wait for all instances to start
  ansible.builtin.include_tasks: wait_for_instance.yml
  loop: "{{ groups[elasticstack_elasticsearch_group_name] }}"

- name: Restart if Elasticsearch was already running
  when:
    - not elasticsearch_freshstart.changed | bool
    - not elasticsearch_freshstart_security.changed | bool
  block:
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
      tags:
        - certificates
        - renew_ca
        - renew_es_cert

    - name: Wait for all instances to start
      ansible.builtin.include_tasks: wait_for_instance.yml
      loop: "{{ groups[elasticstack_elasticsearch_group_name] }}"
      tags:
        - certificates
        - renew_ca
        - renew_es_cert

- name: Check for passwords being set
  ansible.builtin.stat:
    path: "{{ elasticstack_initial_passwords }}"
  delegate_to: "{{ elasticstack_ca_host }}"
  register: elasticsearch_passwords_file

- name: Setting elasticsearch_http_protocol
  ansible.builtin.set_fact:
    elasticsearch_http_protocol: "https"
  when: elasticsearch_http_security

- name: Check for API with bootstrap password
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}"
    user: elastic
    password: "{{ elasticsearch_bootstrap_pw }}"
    validate_certs: false
  register: elasticsearch_api_status_bootstrap
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  when:
    - not elasticsearch_passwords_file.stat.exists | bool
    - groups[elasticstack_elasticsearch_group_name] | length > 1
  until: elasticsearch_api_status_bootstrap.json.cluster_name is defined
  retries: 5
  delay: 10

# We need this check twice. One to wait for the API to be actually available. And a second time to
# check the actual return code. Should not cause a huge delay.

- name: Check for cluster status with bootstrap password
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cluster/health?pretty"
    user: elastic
    password: "{{ elasticsearch_bootstrap_pw }}"
    validate_certs: false
  register: elasticsearch_cluster_status_bootstrap
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  when:
    - not elasticsearch_passwords_file.stat.exists | bool
    - groups[elasticstack_elasticsearch_group_name] | length > 1
  until: elasticsearch_cluster_status_bootstrap.json.status == "green"
  retries: 5
  delay: 10

- name: Fetch Elastic password # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    grep "PASSWORD elastic" {{ elasticstack_initial_passwords }} |
    awk {' print $4 '}
  register: elasticstack_password
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  delegate_to: "{{ elasticstack_ca_host }}"
  when: elasticsearch_passwords_file.stat.exists | bool

- name: Check for API availability with elastic password
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}"
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: false
  register: elasticsearch_api_status
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  when:
    - elasticsearch_passwords_file.stat.exists | bool
    - groups[elasticstack_elasticsearch_group_name] | length > 1
  until: elasticsearch_api_status.json.cluster_name is defined
  retries: 20
  delay: 10

- name: Work around low ressources on CI/CD nodes
  when: ansible_virtualization_type == "container" or ansible_virtualization_type == "docker"
  block:
    # Free up some space to let elsticsearch allocate replica in GitHub Action
    - name: Remove cache
      ansible.builtin.command: >
        rm -rf /var/cache/*
      changed_when: false

    - name: Set persistent watermarks to very high values in Docker # noqa: risky-shell-pipe
      ansible.builtin.shell: >
        if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
        curl
        -k
        -X PUT
        "{{ elasticsearch_http_protocol }}://elastic:{{ elasticstack_password.stdout }}@{{ elasticsearch_api_host }}:9200/_cluster/settings"
        -H 'Content-Type: application/json' -d
        '
        {
          "persistent": {
            "cluster.routing.allocation.disk.watermark.low": "97%",
            "cluster.routing.allocation.disk.watermark.high": "98%",
            "cluster.routing.allocation.disk.watermark.flood_stage": "99%",
            "cluster.routing.allocation.disk.watermark.flood_stage.frozen": "99%"
          }
        }
        '
      changed_when: false
      no_log: "{{ elasticstack_no_log }}"
      when:
        - elasticstack_password.stdout is defined

# We need this check twice. One to wait for the API to be actually available. And a second time to
# check the actual return code. Should not cause a huge delay.

- name: Check for cluster status with elastic password
  ansible.builtin.uri:
    url: "{{ elasticsearch_http_protocol }}://{{ elasticsearch_api_host }}:{{ elasticstack_elasticsearch_http_port }}/_cluster/health?pretty"
    user: elastic
    password: "{{ elasticstack_password.stdout }}"
    validate_certs: false
  register: elasticsearch_cluster_status
  changed_when: false
  no_log: "{{ elasticstack_no_log }}"
  when:
    - elasticsearch_passwords_file.stat.exists | bool
    - groups[elasticstack_elasticsearch_group_name] | length > 1
  until: elasticsearch_cluster_status.json.status == "green"
  retries: 20
  delay: 10

- name: Leave a file showing that the cluster is set up
  ansible.builtin.template:
    dest: "{{ elasticsearch_initialized_file }}"
    src: elasticsearch_initialized.j2
    owner: root
    group: root
    mode: "0600"

- name: Set var that cluster is set up
  ansible.builtin.set_fact:
    elaticsearch_cluster_set_up: true

- name: Create initial passwords # noqa: risky-shell-pipe
  ansible.builtin.shell: >
    if test -n "$(ps -p $$ | grep bash)"; then set -o pipefail; fi;
    /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b >
    {{ elasticstack_initial_passwords }}
  when: inventory_hostname == elasticstack_ca_host
  no_log: "{{ elasticstack_no_log }}"
  args:
    creates: "{{ elasticstack_initial_passwords }}"

# It would be better to create and set the permissions before generating the passwords. But this would
# break the logic that relies on the file being absent when no passwords are set
- name: Set permissions on passwords file
  ansible.builtin.file:
    path: "{{ elasticstack_initial_passwords }}"
    owner: root
    group: root
    mode: 0600
  when: inventory_hostname == elasticstack_ca_host

# Maybe make sure that Elasticsearch is using the right protocol http(s) to connect, even in newly setup clusters
